services:
    mysql:
        image: mysql:8
        container_name: mysql-server
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: root
        network_mode: host
        ports:
            - "3306:3306"
        volumes:
            - ./mysql-data:/var/lib/mysql
